### ISSUE TITLE
Update documentation to include explicit example of how to query staged data

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#100]
## 💪 Motivation
So I can check what is staged.

## 📖 Additional Details

Cannot figure out how to do this. Need this documented in the Registry documentation and linked from the Search API documentation (since you cannot query the staged data through the API).

Should be added somewhere here: https://nasa-pds.github.io/registry/user/update_status.html#update-archive-status

## ⚖️ Acceptance Criteria
**Given** a staged bundle / set of products
**When I perform** a query defined in the documentation
**Then I expect** to see all staged products in OpenSearch

**Comment by jimmie** [comment]
@al-niessner - I think Jordan is looking for a query to be issued directly to OpenSearch (since, as he says in the use-case "you cannot query the staged data through the API"). I will put something together later today if I can slay my current dragons.

**Comment by al-niessner** [comment]
@jimmie @jordanpadams 

If you want raw opensearch:

```
curl --insecure --location --request GET 'https://localhost:9200/registry/_search' --header 'Accept: application/json' --header 'Content-Type: application/json' --user admin:admin -d @Projects/PDS/staged.json
```

where the file `@Projects/PDS/staged.json` is:

```
{
  "from": 0,
  "size": 10,
  "query": {
    "bool": {
      "must": [
        {
          "term": {
            "ops:Tracking_Meta/ops:archive_status": {
              "value": "staged",
              "boost": 1
            }
          }
        }
      ],
      "adjust_pure_negative": true,
      "boost": 1
    }
  },
  "_source": {
    "includes": [
        "lid", "lidvid"
    ],
    "excludes": [
      "ops:Label_File_Info/ops:blob",
      "ops:Label_File_Info/ops:json_blob"
    ]
  }
}
```

**Comment by jimmie** [comment]
@al-niessner - thank you! That was a lot faster than I could have done (the nuances of ES/OS query language remain out of my mental grasp).

@jordanpadams - can you confirm this is what you were looking for?

**Comment by jordanpadams** [comment]
👍 the only catch here is this is completely unusable. we will need to add this functionality to registry-manager directly instead of just documenting.

**Comment by jordanpadams** [comment]
remove @alexdunnjpl as assignee. ticket created in registry-mgr: https://app.zenhub.com/workspace/o/nasa-pds/registry-mgr/issues/59

**Comment by tloubrieu-jpl** [comment]
We can now use the dashboards for that.
