### ISSUE TITLE
API and OpenSearch are not giving similar results

### ISSUE THREAD

**Issue by plawton-umd** [NASA-PDS/registry#117]
## 🐛 Describe the bug

I deleted a package ("efdc71bc-bbb2-49d2-b8b1-8b4ff971acde").  I reloaded the dataset 
(urn:nasa:pds:epoxi_mri with new package id "0cc6a610-6c36-47a1-b5c1-02dd88ce2475").
OpenSearch shows the new upload with the corrected file_ref path.  The API is still showing 
old upload with the incorrect file_ref and label_url paths.

## 📜 To Reproduce
1. To see the api's response, type
```
curl https://pds.nasa.gov/api/search-sbnumd/1.0/bundles/urn:nasa:pds:epoxi_mri | json_pp 
```
3. Note the package_id value, harvest_date_time value, file_ref value, and label_url value (last 2 items have the incorrect values that I am correcting).
4. To see the OpenSearch response, type (with your own user name)

              
```
curl -u <your_username>   \
'https://search-sbnumd-prod-o5i2rnn265gnwmv2quk4n7uram.us-west-2.es.amazonaws.com/registry/_search?q={_id:"urn:nasa:pds:epoxi_mri::1.0"}' | json_pp
```
(note: this system is messing up the above command a bit)

4. Note the package_id value, harvest_date_time value, and file_ref value.  These are what are expected in the api output.

## 🕵️ Expected behavior

The api output values should match the OpenSearch values

## 📚 Version of Software Used

Registry Manager version: 4.5.0
Build time: 2022-09-21T18:49:44Z

## 🖥 System Info
 
Linux

n/a

---

**Comment by jordanpadams** [comment]
@plawton-umd I think this is a caching issue. I am going to close this ticket as a bug, and instead create a new requirement for us to update registry manager to force a cache flush whenever archive status is set. If you try that curl command now, it works as expected. @jimmie do we have any idea how long it takes for the cache to flush? we may want to document that somewhere.

also, per this
> (note: this system is messing up the above command a bit)

You can use the GitHub markdown code blocks to fix this in the future: https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
