### ISSUE TITLE
As a user, I want to view dashboard report of bundles with archive status and other tracking information

### ISSUE THREAD

**Issue by scholes-ds** [NASA-PDS/registry#130]
## 🧑‍🔬 User Persona(s)

Node Registry Admin

## 💪 Motivation
This will improve efficiency and help Node Registry Admins monitor the status of their bundles in the registry

## 📖 Additional Details
It would be very helpful to have a concise report from the registry manager or an online portal that provides a list of bundles with archive status (including staged or filtered to staged), with additional helpful information. This will help quickly verify progress without running scripts.
Including: 
Bundle Lid, current version or tracked versions, package id (does that change for each reload?), entry count of products, collections, archive link, etc. Perhaps error count would be useful, if it applies.  

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by scholes-ds** [comment]
Displaying the last date the bundle contents were updated through harvest would be very helpful. In addition, links to eventual error logs and activity history (dates updated through harvest and status updated) would be nice.

**Comment by tloubrieu-jpl** [comment]
That would be part of a new registry visualization component (e.g. with kibana).

This development will be tabled until remove the Cross Cluster Search from the architecture.

**Comment by jordanpadams** [comment]
This is good to go for now.
