### ISSUE TITLE
Harvest is throwing errors of "Forbidden index write"

### ISSUE THREAD

**Issue by scholes-ds** [NASA-PDS/registry#132]
## 🐛 Describe the bug
After days of running harvest, I have started encountering "FORBIDDEN/8/index write (api) errors on consistent runs of harvest. This is using the stand alone harvest. I wonder if my access is being blocked somewhere along the connection due to all the traffic? Or is a buffer full?

This error occured while running harvest against this large bundle:
**https://pds-geosciences.wustl.edu/mro/urn-nasa-pds-mro_sharad_simulations/**
The error is also showing up with other processing at this time. 

## 🕵️ Expected behavior
It shouldn't be throwing these errors. 

## 📚 Version of Software Used
Harvest version 3.7.2
Build time: 2022-10-14t17:26:27Z

## 🩺 Test Data / Additional context
https://pds-geosciences.wustl.edu/mro/urn-nasa-pds-mro_sharad_simulations/
Also throwing error on 
https://pds-geosciences.wustl.edu/mer/mer1-m-pancam-3-radcal-sci-v2/mer1pc_1002/

##  🏞Screenshots
**Example Harvest output:**
[INFO] Processing product \\isilon-pri-data\pds-san\data\mro\urn-nasa-pds-mro_sharad_simulations\data\s_0595xx\s_05955501\s_05955501_emap.xml
[INFO] Processing product \\isilon-pri-data\pds-san\data\mro\urn-nasa-pds-mro_sharad_simulations\data\s_0595xx\s_05955501\s_05955501_rtrn.xml
[INFO] Processing product \\isilon-pri-data\pds-san\data\mro\urn-nasa-pds-mro_sharad_simulations\data\s_0595xx\s_05955501\s_05955501_sim.xml
[INFO] Processing product \\isilon-pri-data\pds-san\data\mro\urn-nasa-pds-mro_sharad_simulations\data\s_0595xx\s_05955502\s_05955502_emap.xml
[INFO] Processing product \\isilon-pri-data\pds-san\data\mro\urn-nasa-pds-mro_sharad_simulations\data\s_0595xx\s_05955502\s_05955502_rtrn.xml
[INFO] Processing product \\isilon-pri-data\pds-san\data\mro\urn-nasa-pds-mro_sharad_simulations\data\s_0595xx\s_05955502\s_05955502_sim.xml
[INFO] Processing product \\isilon-pri-data\pds-san\data\mro\urn-nasa-pds-mro_sharad_simulations\data\s_0595xx\s_05956101\s_05956101_emap.xml
[INFO] Processing product \\isilon-pri-data\pds-san\data\mro\urn-nasa-pds-mro_sharad_simulations\data\s_0595xx\s_05956101\s_05956101_rtrn.xml
[INFO] Processing product \\isilon-pri-data\pds-san\data\mro\urn-nasa-pds-mro_sharad_simulations\data\s_0595xx\s_05956101\s_05956101_sim.xml
[INFO] Processing product \\isilon-pri-data\pds-san\data\mro\urn-nasa-pds-mro_sharad_simulations\data\s_0595xx\s_05956401\s_05956401_emap.xml
[INFO] Processing product \\isilon-pri-data\pds-san\data\mro\urn-nasa-pds-mro_sharad_simulations\data\s_0595xx\s_05956401\s_05956401_rtrn.xml
[INFO] Processing product \\isilon-pri-data\pds-san\data\mro\urn-nasa-pds-mro_sharad_simulations\data\s_0595xx\s_05956401\s_05956401_sim.xml

...

[ERROR] LIDVID = urn:nasa:pds:mro_sharad_simulations:data:s_05955501_emap::1.0, Message = index [registry] blocked by: [FORBIDDEN/8/index write (api)];
[ERROR] LIDVID = urn:nasa:pds:mro_sharad_simulations:data:s_05955501_rtrn::1.0, Message = index [registry] blocked by: [FORBIDDEN/8/index write (api)];
[ERROR] LIDVID = urn:nasa:pds:mro_sharad_simulations:data:s_05955501_sim::1.0, Message = index [registry] blocked by: [FORBIDDEN/8/index write (api)];
[ERROR] LIDVID = urn:nasa:pds:mro_sharad_simulations:data:s_05955502_emap::1.0, Message = index [registry] blocked by: [FORBIDDEN/8/index write (api)];
[ERROR] LIDVID = urn:nasa:pds:mro_sharad_simulations:data:s_05955502_rtrn::1.0, Message = index [registry] blocked by: [FORBIDDEN/8/index write (api)];
[ERROR] LIDVID = urn:nasa:pds:mro_sharad_simulations:data:s_05955502_sim::1.0, Message = index [registry] blocked by: [FORBIDDEN/8/index write (api)];
[ERROR] LIDVID = urn:nasa:pds:mro_sharad_simulations:data:s_05956101_emap::1.0, Message = index [registry] blocked by: [FORBIDDEN/8/index write (api)];
[ERROR] LIDVID = urn:nasa:pds:mro_sharad_simulations:data:s_05956101_rtrn::1.0, Message = index [registry] blocked by: [FORBIDDEN/8/index write (api)];
[ERROR] LIDVID = urn:nasa:pds:mro_sharad_simulations:data:s_05956101_sim::1.0, Message = index [registry] blocked by: [FORBIDDEN/8/index write (api)];
[ERROR] LIDVID = urn:nasa:pds:mro_sharad_simulations:data:s_05956401_emap::1.0, Message = index [registry] blocked by: [FORBIDDEN/8/index write (api)];
[ERROR] LIDVID = urn:nasa:pds:mro_sharad_simulations:data:s_05956401_rtrn::1.0, Message = index [registry] blocked by: [FORBIDDEN/8/index write (api)];

## 🖥 System Info
 - OS: Windows Server 2019

---

**Comment by jordanpadams** [comment]
@jimmie is working with SAs to add more space to the cluster to fix this issue.

**Comment by jimmie** [comment]
Storage on each OpenSearch node has been increased to 100GB (total of 300GB). Need to reshard the registry index.

**Comment by jimmie** [comment]
The registry index was rebuilt to use 6 shards across the 3 100GB volumes. There should be sufficient space and the ability to write additional records restored.

**Comment by tloubrieu-jpl** [comment]
@scholes-ds I am closing this ticket since you should not have this error anymore. Let us know if otherwise. 

Thanks and sorry for the interruption of the service.
