### ISSUE TITLE
ref_collection_lidvid field in some node registries populated using older versions of registry loader tools create string fields in the schema vs. the expected list types

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#159]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

I believe GEO has some of these metadata fields, as an example for updating this.

### 🕵️ Expected behavior

All fields are lists

### 📜 To Reproduce
1. Query a registry that contains String fields instead of list fields
2. Node that they are String fields and should be lists :-)

### 🖥 Environment Info

```bash
N/A
```

### 📚 Version of Software Used

N/A

### 🦄 Related requirements

https://github.com/NASA-PDS/registry-common/issues/29

### ⚙️ Engineering Details

N/A

**Comment by jimmie** [comment]
This would require a script to determine which documents have atomic values and convert them to lists. Since the API (and I assume ingestion tools) have been modified to tolerate heterogeneous types we are going to punt on this for now.
