### ISSUE TITLE
Add CloudWatch event for monitoring provenance script failure

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#167]
## 💡 Description

follow on to TBD issue

**Comment by tloubrieu-jpl** [comment]
@jimmie is waiting for an action of the SA's

**Comment by jordanpadams** [comment]
@jimmie to confirm, per the email we received this AM, this is good?

**Comment by jimmie** [comment]
Yes, it confirms that the alert workflow is working.

**Comment by tloubrieu-jpl** [comment]
@jimmie was there a pull request to add the cloud wathc event to the terraform scripts ?

**Comment by tloubrieu-jpl** [comment]
I am creating a specific ticket https://github.com/NASA-PDS/registry-sweepers/issues/9 to have the event configured in terraform.
