### ISSUE TITLE
As a manager, I want to see the progress of data sets ingested into registry vs. legacy registry

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#168]
### Checked for duplicates

No - I haven't checked

### 🧑‍🔬 User Persona(s)

Discipline node or Engineering node manager.

### 💪 Motivation

...so that I can report on the progress of ingestion in the registry and compare with the total number of products available in the legacy registry.

### Acceptance Criteria

**Given** the manager's registry guide 
**When I perform** a request on the dashboard
**Then I expect** to find a dashboard showing the progress of ingestion in the registry 
**Then I expect** to compare with it what is in the legacy registry

### ⚙️ Engineering Details

Use the kibana dashbaords

**Comment by nutjob4life** [comment]
Work pending

**Comment by nutjob4life** [comment]
TL will work on this

**Comment by jordanpadams** [comment]
Initial requirement considered complete per "Legacy Dashboard" on search-en Kibana
