### ISSUE TITLE
As a user, I want the registry to have 99.9999999% uptime

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#176]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Node Operator, EN Operator, Manager

### 💪 Motivation

...so that I can ensure the registry/OpenSearch is deployed in such a manner that it will recover from a critical failure ensuring our uptime goals.

### Acceptance Criteria

**Given** 
**When I perform** 
**Then I expect**

**Comment by jordanpadams** [comment]
Per https://github.com/NASA-PDS/registry/issues/211, we have setup notifications to ensure minimal registry crashes. Have also increased storage capacity for OpenSearch instances to avoid crashes. Closing this as completed for the time being. A move to OpenSearch serverless will hopefully add even more robustness here.

**Comment by tloubrieu-jpl** [comment]
I&T cannot test that but we need to add a requirement "As a manager, I want to check the availability statistics for the registry"
