### ISSUE TITLE
Provenance script failing on production registry

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#180]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I did a query for some NAIF SPICE data, I was unable to get a response

### 🕵️ Expected behavior

I expected to get a product back

### 📜 To Reproduce

1. Go to https://search-naif-prod-pm7hsg36wqejex3whlnpj3d6ma.us-west-2.es.amazonaws.com/_dashboards/app/discover#/?_g=(filters:!(),query:(language:kuery,query:''),refreshInterval:(pause:!t,value:0),time:(from:now-10y,to:now))&_a=(columns:!('ops:Provenance%2Fops:superseded_by'),filters:!(),index:'04de9280-9067-11ed-aa4d-b9457fec4322',interval:auto,query:(language:kuery,query:'lidvid:%22urn:nasa:pds:mars2020.spice*%22'),sort:!())
2. Or query for `lid:"urn:nasa:pds:mars2020.spice"`, and not that there are 2 versions with no `superseded_by` set. I think this is confusing the API.

### 🩺 Test Data / Additional context

<img width="1182" alt="Screenshot 2023-04-04 at 7 55 47 AM" src="https://user-images.githubusercontent.com/33492486/229832958-5e8614f8-98d4-407e-a091-e9ca5a96d811.png">

**Comment by tloubrieu-jpl** [comment]
@jordanpadams, @jimmie 

The superseeded_by tag looks now good (since the work done by @jimmie on ticket https://github.com/NASA-PDS/registry-api/issues/305 maybe).

But there is no archive_status available, see screnshot of the products in kibana:
 
<img width="1549" alt="image" src="https://user-images.githubusercontent.com/60993872/230455999-2a2fef83-6174-4b42-88a5-301371630755.png">

Which makes the product unavailable in the API.

I will investigage further why that is.

**Comment by jimmie** [comment]
@alexdunnjpl and I were discussing the missing archive_status' yesterday in the context of [registry-api#305](https://github.com/NASA-PDS/registry-api/issues/305). There are two factors that were at hand in that issue; 1) inability to access a document via lidvid and 2) out of whack superseded_by and missing archive_status. As you noted @tloubrieu-jpl, the issue w/ the vid hierarchy has been fixed (after fixing the lidvid issue). We suspect the missing archive_status _may_ be a result of the lidvid issue, but we're not sure. While we're close to having the issues resolved, the whole scenario is highly unusual and I really don't have any theories on how it all came to be.

**Comment by tloubrieu-jpl** [comment]
Thanks @jimmie, let's discuss that at the breakout.
Maybe we should deploy a newer version of the API so to have API known bugs out of our way...

**Comment by jordanpadams** [comment]
follow on to https://github.com/nasa-pds/registry-api/issues/305

**Comment by tloubrieu-jpl** [comment]
This bug is fixed by :


See screenshot:
<img width="1073" alt="image" src="https://user-images.githubusercontent.com/60993872/234969482-f293375e-2b01-4025-9482-d5849ca09485.png">
