### ISSUE TITLE
Rework Registry+API Architecture Diagram in LucidChart

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#189]

**Comment by jimmie** [comment]
original google slides version here: https://docs.google.com/presentation/d/1222cD7mclEYA50btszHzgaiahOkkOMJO96F87vQcRC4/edit?usp=sharing

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @sjoshi-jpl , I was also thinking we could have detailed AWS diagram managed in github with code, together with the terraform global script. I found this tool https://diagrams.mingrammer.com/docs/getting-started/installation

I did not try yet.

**Comment by sjoshi-jpl** [comment]
@jordanpadams @tloubrieu-jpl the registry-api diagram has been moved our to LucidChart - https://lucid.app/lucidchart/d2d7eb2a-352b-4105-81d6-5694f3d50f8a/edit?invitationId=inv_cb274122-3dbb-43bf-8535-c5700843ee35

Additionally, I also experimented with [mingrammer](https://diagrams.mingrammer.com/docs/getting-started/installation) for diagram as a code setup but visually Lucidchart still takes the prize. I can demo this during our stand-up.

**Comment by jordanpadams** [comment]
status: diagram complete. onto review for @tloubrieu-jpl and @jordanpadams
