### ISSUE TITLE
registry-manager set-archive-status returned time out

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#192]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

When I did a registry-manager set-archive-status, the system returned a time out, see command here:

```
3: \Users \scholes›registry-manager set -archive-status -status archived -packageId "48031671-897e-4a42-9bdf-ed9112c65f8c"
-es https: / / search-geo-prod-6iz61wiw6luyffpsq52ndsrtbu.us-west -2.es.amazonaws.com :443 -auth E: /opt/configs22/dan-auth.cf
¡ERRORI Missing requined panameter "- Lidvid*
c: \Users\scholes›registry-manager set-archive-status -status archived -lidvid "urn:nasa:pds:mars2020 sherloc: :1.0"
-es h
ttps://search-geo-prod-6iz61wiw6luffpsq52ndsrtbu.us-west-2.es.amazonaws.com:443-auth E: /opt/configs22/dan-auth.cfg
(INFO] Setting product status. LIDVID - urn:nasa:pds:mars2020_sherloc::1.0,
status = archived
[WARN] Collection urn:nasa:pds:mars2020_sherloc:data_aci::6.0 doesn't have primary products.
[ERROR] 10,000 milliseconds timeout on connection http-outgoing-1 [ACTIVE]
c: \Users\ scholes>
4:00 PM
4/24/2023
```

The command was run successfully after that.

### 🕵️ Expected behavior

I expected the command to succeed the first time.

### 📜 To Reproduce

Not reproduced

### 📚 Version of Software Used

registry 1.1

### 🩺 Test Data / Additional context

Bug reported by Dan Scholes from GEO node.

### 🦄 Related requirements

🦄 #xyz

**Comment by jordanpadams** [comment]
numerous other timeout bugs are being tracked for this. closing this as duplicate for those
