### ISSUE TITLE
Add provenance script to the lucidchart AWS deployment diagram

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#195]
## 💡 Description

See https://lucid.app/lucidchart/d2d7eb2a-352b-4105-81d6-5694f3d50f8a/edit?invitationId=inv_cb274122-3dbb-43bf-8535-c5700843ee35&page=0_0#

The provenance script is code is in in the registry-sweeper repository.

**Comment by sjoshi-jpl** [comment]
Added - https://lucid.app/lucidchart/d2d7eb2a-352b-4105-81d6-5694f3d50f8a/edit?invitationId=inv_cb274122-3dbb-43bf-8535-c5700843ee35&page=66uWzmvPQEeN#

**Comment by alexdunnjpl** [comment]
N.B. (if this changes anything) there will be multiple metadata sweepers shortly (see registry-sweepers #10)
