### ISSUE TITLE
Enable I&T to use and update registry-api automated tests

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#199]
## 💡 Description

- https://github.com/NASA-PDS/devops/issues/35
- https://github.com/NASA-PDS/registry/issues/198
- https://github.com/NASA-PDS/registry/issues/200
- https://github.com/NASA-PDS/registry/issues/201

**Comment by jordanpadams** [comment]
All sub-tasks completed. I&T are actively adding new data to the registry test data set
