### ISSUE TITLE
B14.0 Update the postman test suite with all the requirement tests

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#200]
## 💡 Description

Postman collection organization, and content → Gary/Miguel
Requirements: We should have a non regression test for each closed requirements in https://github.com/NASA-PDS/pds-api/issues?q=is%3Aissue+is%3Aclosed+label%3Arequirement but we can start with the closed requirements in the RDD

**Comment by jordanpadams** [comment]
@gxtchen @miguelp1986 per the last sprint review, you should have some direction to get started here.

**Comment by miguelp1986** [comment]
@jordanpadams I've already been adding tests to Postman, but currently turning my focus on preparing for TRR. Thomas' presentation yesterday helped me out with tests that require me to add test data, so that was very helpful for some of the tests I've been trying to add.

**Comment by nutjob4life** [comment]
Postman tests are pretty much done! Just some merge conflicts.
