### ISSUE TITLE
Design scalable, multi-tenant opensearch

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#212]
## 💡 Description

Consider options to automatically add nodes to the opensearch cluster or use AWS serverless opensearch.

The objective is to avoid service outage due to lack of resources and keep to a minimum the manual configuration.

**Comment by jordanpadams** [comment]
The design has been completed for some time. See parent task for more details on the work being done. https://github.com/NASA-PDS/registry/issues/185
