### ISSUE TITLE
Increase disk space for ATM opensearch

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#213]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

New data cannot be harvested successfully.

### 🕵️ Expected behavior

There should be enough space for new ATM datasets

### 🖥 Environment Info

Deployment in production

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl has created a ticket to the SAs to increase the disk space from 40Gb to 60Gb.

We don't need to plan for disk space beyond a few month from now since we will switch o a multi-tenant configuration after that.

**Comment by sjoshi-jpl** [comment]
This is completed and can closed.

**Comment by tloubrieu-jpl** [comment]
@jordanpadams @viviant100 we need to define a strategy to test the AWS deployment related tickets
