### ISSUE TITLE
Enhance cost monitoring, alerting, and error handling for Registry and Registry Sweepers

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#214]
## 💡 Description

- https://github.com/NASA-PDS/registry-sweepers/issues/34
- https://github.com/NASA-PDS/registry-sweepers/issues/31
- https://github.com/NASA-PDS/registry-sweepers/issues/40
- https://github.com/NASA-PDS/registry-sweepers/issues/30
- ~https://github.com/NASA-PDS/registry-sweepers/issues/39~

**Comment by jordanpadams** [comment]
@tloubrieu-jpl I transferred this ticket without realizing it was an Epic. Do you remember the tickets you created?

**Comment by tloubrieu-jpl** [comment]
@jordanpadams I did not created tickets yet, I don't think @sjoshi-jpl  created his either but we should have some in https://github.com/NASA-PDS/monitoring

**Comment by alexdunnjpl** [comment]
@jordanpadams @tloubrieu-jpl could one of y'all please add [registry-sweepers #40](https://github.com/NASA-PDS/registry-sweepers/issues/40) to this epic?

I tried, but the board was acting weird and wouldn't load issues (at least, the way I was trying to use it)

**Comment by jordanpadams** [comment]
@alexdunnjpl done.

**Comment by jordanpadams** [comment]
📆 July status: New tasks added to release plan. To be completed in B14.0 delivery.

**Comment by jordanpadams** [comment]
📆 August status: Deferring sub-task https://github.com/NASA-PDS/registry-sweepers/issues/39 per https://github.com/NASA-PDS/registry-sweepers/issues/39#issuecomment-1661368230. Will revisit down the road if it is determined to be needed.
