### ISSUE TITLE
Add registry costs to the PDS EN Cloud spreadsheet

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#218]
## 💡 Description

- [x] Includes existing costs (Jimmie's spreadsheet)
- [x] new lambda orchestrator for registry-sweeper

**Comment by sjoshi-jpl** [comment]
@jordanpadams @tloubrieu-jpl there are multiple cost model documents on Google Docs. Can you please tell me which one I need to update?

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl is making progresses on this ticket.

**Comment by tloubrieu-jpl** [comment]
Ready for review

**Comment by jordanpadams** [comment]
New costs added to spreadsheet
