### ISSUE TITLE
Setup OIDC Authentication for MCP

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/registry#222]
Work with MCP SA team to setup an IAM role for OIDC authentication. Similar to what we have in [NGAP](https://wiki.jpl.nasa.gov/pages/viewpage.action?pageId=779056783).

The role needs to be an AssumeRole that can be used for authenticating to MCP via GitHub Actions. 

Based on the latest conversation with MCP SA team, we need to provide them with an IAM (least privilege) policy that will be attached to this role and grant our team access to deploy AWS resources. To do this, we need to come up with the list of services our PDS project uses in AWS and then define a set of permissions for each service.

**Comment by jordanpadams** [comment]
@sjoshi-jpl when creating tickets, please try to use the issue templates like those specified here: https://github.com/NASA-PDS/registry/issues

the issue templates don't work in the Zenhub interface, so they should not be used.

**Comment by jordanpadams** [comment]
@nutjob4life next up after https://github.com/NASA-PDS/registry/issues

**Comment by nutjob4life** [comment]
Hi @jordanpadams, I'm going to add @sjoshi-jpl to this as well since I don't have the NGAP, MCP, or role-provisioning experience in IAM. Conceptually I think I know how this'll work, but _together_ we'll be able to make progress on it.

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl is updating the IAM role.

**Comment by sjoshi-jpl** [comment]
Unable to create a new identity provider in MCP. Will need SA to create it for us.

**Comment by jordanpadams** [comment]
Status: Awaiting SA support on this topic

**Comment by jordanpadams** [comment]
Status: Ping from MCP they are working on it right now

**Comment by sjoshi-jpl** [comment]
Setup complete for OIDC IdP and IAM role trust policy. However, still receiving error while using it. Working with MCP on a resolution.

**Comment by sjoshi-jpl** [comment]
OIDC setup fully tested and functional

**Comment by tloubrieu-jpl** [comment]
I am closing this ticket.
