### ISSUE TITLE
OpenSearch Serverless Setup in MCP

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/registry#223]
## 💡 Description

Work with MCP SA team and AWS to setup OpenSearch Serverless collection in MCP. The collection should host all OS domains (pds nodes) and should be scalable and highly-available.

Tightly coupled if not duplicate issue: https://github.com/NASA-PDS/registry/issues/212

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl created a case with AWS.

**Comment by tloubrieu-jpl** [comment]
Tushar from AWS (JPL account) is discussing with his colleagues from NASA account. No feedback yet.

**Comment by tloubrieu-jpl** [comment]
A meeting is scheduled tomorrow with AWS support.

**Comment by tloubrieu-jpl** [comment]
Meeting has happened.

@sjoshi-jpl is analyzing how to migrate data (including users) using logstash.

A ticket with MCP is also open regarding plugins which are missing.

**Comment by tloubrieu-jpl** [comment]
A call with AWS is organized Wednesday at 1pm.

**Comment by jordanpadams** [comment]
Status: Per meeting with support team. Waiting on AWS support to provide some workaround solutions.

**Comment by jordanpadams** [comment]
Status: Continues to be in work. Looking to follow up with AWS support. Blocked by AWS support lack of response.

**Comment by jordanpadams** [comment]
Status: Still blocked. AWS internal team is working on it.

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl is going to look at a role aspect that he missed before.
He also requested a phone call with AWS.

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl had a meeting with AWS earlier today but there is still an error.

**Comment by tloubrieu-jpl** [comment]
The error has been submitted to AWS. Waiting for their feedback.

**Comment by jordanpadams** [comment]
Status: Discuss how we want to secure OpenSearch Serverless

**Comment by sjoshi-jpl** [comment]
Update : Web service + API Gateway + Cognito is the architecture we have decided on for both read / write access based on the call with Jordan / Ramesh. I will be working with @ramesh-maddegoda to create tasks to start development.

**Comment by jordanpadams** [comment]
Initial OpenSearch Serverless setup has been completed, so considering this task done. See parent Epic for additional sub-tasks created to support the architecture noted above.
