### ISSUE TITLE
Write documentation and Training for Registry monitoring

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/registry#224]
## 💡 Description

Write [documentation](https://wiki.jpl.nasa.gov/display/PDSEN/ECS+Configuration+and+Monitoring) for monitoring of ECS Registry-Sweepers Cluster / Tasks as well as administering CloudWatch alarms and lambdas for registry (api and sweeper services).

Once documentation is completed, setup training with SA, Operations and Dev Team. Decide on a monitoring process and appoint a specific person from one of these teams to monitor these alerts regularly.

**Comment by jordanpadams** [comment]
@sjoshi-jpl has been working on documentation. planning training for SA team for early next week.

**Comment by tloubrieu-jpl** [comment]
This ticket can be closed, although no user of the dashboard have been clearly identified beside @sjoshi-jpl .
We are waiting for the operation team to be trained to monitor applications on the cloud doing things automatically rather that doing things manually as currently done in most cases.
