### ISSUE TITLE
Registry-Sweepers Multiple Updates Statements Detected - NOT retry-related

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/registry#225]
## 💡 Description

Registry-Sweepers monitoring lambda has reported following error for multiple log groups in CloudWatch and needs to be fixed.

```
pds.registrysweepers.ancestry::ERROR::Multiple updates detected for doc_id
```

**Comment by alexdunnjpl** [comment]
@sjoshi-jpl could you please include extra detail?
- the node from which this node was produced (name and OS host/url)
- at least one full log message including the affected doc id and the two conflicting update content strings

**Comment by sjoshi-jpl** [comment]
@alexdunnjpl Sure. So far the nodes that this error has occurred on are PPI and GEO. Below are the full log messages:

PPI

```
Error found in log group '/ecs/pds-ppi-prod-registry-sweeper-task':

Timestamp (UTC): 2023-08-30 19:49:51.860000
Log Stream: ecs/pds-ppi-prod-registry-sweeper-container/014a95fd09c94b9cb3ee76330181df4b
Error Message: 2023-08-30 19:49:51,860::pds.registrysweepers.ancestry::ERROR::Multiple updates detected for doc_id urn:nasa:pds:cassini-caps-derived:document::1.0 - cannot create update! (got {'ops:Provenance/ops:parent_bundle_identifier': [], 'ops:Provenance/ops:parent_collection_identifier': ['urn:nasa:pds:cassini-caps-derived:document::1.0']}, {'ops:Provenance/ops:parent_bundle_identifier': [], 'ops:Provenance/ops:parent_collection_identifier': []} already exists)
```

GEO 

```
Error found in log group '/ecs/pds-geo-prod-registry-sweeper-task':

Timestamp (UTC): 2023-08-30 18:39:19.504000
Log Stream: ecs/pds-geo-prod-registry-sweeper-container/9af3f06f49d04b18a8de29b3648c92e2
Error Message: 2023-08-30 18:39:19,504::pds.registrysweepers.ancestry::ERROR::Multiple updates detected for doc_id urn:nasa:pds:mess_mla_raw:data_edr::1.0 - cannot create update! (got {'ops:Provenance/ops:parent_bundle_identifier': ['urn:nasa:pds:mess_mla_raw::1.0'], 'ops:Provenance/ops:parent_collection_identifier': ['urn:nasa:pds:mess_mla_raw:data_edr::1.0']}, {'ops:Provenance/ops:parent_bundle_identifier': ['urn:nasa:pds:mess_mla_raw::1.0'], 'ops:Provenance/ops:parent_collection_identifier': []} already exists)
```

**Comment by jordanpadams** [comment]
@alexdunnjpl @sjoshi-jpl do we know if this has been resolved?

**Comment by alexdunnjpl** [comment]
Updated title to clarify since I keep confusing this issue with the fact that timeouts will result in multiple update writes => db conflicts.

This is related to multiple update statements being generated during processing, prior to db writes.

@sjoshi-jpl is this still occurring?

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl do you know if this is still happening ?

**Comment by sjoshi-jpl** [comment]
@jordanpadams @tloubrieu-jpl @alexdunnjpl these errors are no longer occurring in the logs. I checked for last 4 weeks and I didn't see them for any node.

**Comment by jordanpadams** [comment]
Closing
