### ISSUE TITLE
As a system, I can support up to 25 simultaneous writes from Harvest

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#226]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

System

### 💪 Motivation

...so that I can support better scalability

### Acceptance Criteria

**Given** a running Registry / OpenSearch
**When I perform** multiple simultaneous harvest executions
**Then I expect** OpenSearch to support those writes without error

### ⚙️ Engineering Details

This requirement is intentionally vague. We would like to know what # of simultaneous runs of harvest. Right now, I took at stab at 25, but getting an understanding of where this breaks would be great.

**Comment by miguelp1986** [comment]
@tloubrieu-jpl I'm having problems having my Harvest app, which I've built from the latest release files, talk to my local, Dockerized OpenSearch instance.
When running a test command, I get a certificate error:
```
harvest -c /usr/local/harvest-3.8.0/conf/examples/directories_copy.xml                                                                   ─╯
[SUMMARY] Reading configuration from /usr/local/harvest-3.8.0/conf/examples/directories_copy.xml
[SUMMARY] Output directory: /tmp/harvest/out
[SUMMARY] Elasticsearch URL: https://localhost:9200/, index: registry
[INFO] Connecting to Elasticsearch
[ERROR] Host name 'localhost' does not match the certificate subject provided by the peer (CN=elasticsearch, OU=PDS, O=ORG, L=LA, ST=CALIFORNIA, C=CA)
```
I'm following along with https://nasa-pds.github.io/registry/user/load1.html#standalone-harvest-quick-start.

Attached is my Harvest config file: 
[directories_copy copy.xml.txt](https://github.com/NASA-PDS/registry/files/13200414/directories_copy.copy.xml.txt)

**Comment by miguelp1986** [comment]
I fixed my issue. I added `registry-api `and `elasticsearch` as domains alongside `localhost` in my `/etc/hosts` file. Now Postman works with Registry-Api tests without having to change the `baseUrl` to `localhost` and my Harvest command line tool works with OpeanSearch when I have it pointing to https://elasticsearch:9200 in the config file.

**Comment by tloubrieu-jpl** [comment]
Great ! Thanks @miguelp1986
