### ISSUE TITLE
Fix lambda filters for registry-sweepers and registry-api

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/registry#227]
## 💡 Description

Current lambda filter pattern returns ALL errors (non-container killing errors as well). We need to update the filter pattern to fix the lambda to only send SNS notifications on errors that are killing the container task for registry-api and sweepers.

**Comment by tloubrieu-jpl** [comment]
Registry-sweeper is fixed but registry-api is waiting for https://github.com/NASA-PDS/registry-api/issues/376 to be done.

**Comment by tloubrieu-jpl** [comment]
What can be done now is done, need to create a new ticket after api logs are improved

**Comment by tloubrieu-jpl** [comment]
Follow up ticket created in https://github.com/NASA-PDS/monitoring/issues/12
