### ISSUE TITLE
Setup monitoring for Domain Notifications for all OpenSearch Domains in AWS

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/registry#233]
## 💡 Description

Create a monitoring alarm or trigger that will send SNS email notifications in the event of medium, high or critical severity notifications for every domain within OpenSearch.

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl created a new lambda for the notifications.

**Comment by tloubrieu-jpl** [comment]
It does not work, @sjoshi-jpl needs support from the SAs

**Comment by tloubrieu-jpl** [comment]
Notification work. 2 rules are created on cloudwatch.

We don't have a terraform script for that and we don't care too much since we are investing more on MCP deployments.
