### ISSUE TITLE
Setup Cognito User Pool

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/registry#251]
MCP OpenSearch Setup in Dev - Setup User Pool for Cognito
1. Create a Cognito User Pool
2. Create a Cognito App Client for OpenSearch Serverless

**Comment by tloubrieu-jpl** [comment]
The cognito user pool is created but an IAM role need to be attached to it (which requires MCP SAs)

**Comment by nutjob4life** [comment]
Helping @al-niessner with auth

**Comment by tloubrieu-jpl** [comment]
The cognito pool is setup in dev.
