### ISSUE TITLE
Create Lambda Authorizer for Write Access - OpenSearch Serverless Authentication

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/registry#254]
Create Lambda Authorizer for Write Access (exchange cognito ID token with AWS temporary creds and get signed URLs from IAM). Add source IP filtering based on event details. Check source IP against whitelisted Ips that are part of env variables in Lambda.

**Comment by jordanpadams** [comment]
@sjoshi-jpl do we have a status on this? can we consider this done?

**Comment by sjoshi-jpl** [comment]
This is completed and can be closed.
