### ISSUE TITLE
Create Lambda Authorizer for Read Access - OpenSearch Serverless Authentication

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/registry#255]
Create Lambda Authorizer for Read-Only Access (can also be used by API). Give this lambda read-only permissions to OpenSearch and provide Read-Only credentials. Add source IP filtering based on event details. Check source IP against whitelisted Ips that are part of env variables in Lambda.

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl is investigating errors on the lambda.

**Comment by nutjob4life** [comment]
Sagar working with @al-niessner on this

**Comment by jordanpadams** [comment]
@sjoshi-jpl do we have a status on this? can we consider this done?

**Comment by sjoshi-jpl** [comment]
@jordanpadams This is completed and can be closed.
