### ISSUE TITLE
Setup API Gateway - OpenSearch Serverless Authentication

### ISSUE THREAD

**Issue by sjoshi-jpl** [NASA-PDS/registry#256]
Setup API Gateway for OpenSearch Serverless Authentication in MCP:
    /signed-url (resource1)
        GET (method) --> get-signed-url lambda (write access lambda)
    /registry (resource2)
        GET (method) --> read-registry-lambda (read-only lambda)

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl currently woks on the terraform for the deployment of the API gateway. Shoud be done today or soon.

**Comment by nutjob4life** [comment]
@anilnatha @sjoshi-jpl is troubleshooting an issue with AWS gateway

**Comment by tloubrieu-jpl** [comment]
A wrong path is captured through the argument of the API gateway and transmitted to the lambda function. Will be discussed at the breakout.

**Comment by jordanpadams** [comment]
@sjoshi-jpl do we have a status on this? can we consider this done?

**Comment by sjoshi-jpl** [comment]
@jordanpadams This is completed and can be closed.

**Comment by jordanpadams** [comment]
@sjoshi-jpl copy that.
