### ISSUE TITLE
Deploy Multi-tenant Registry to production and sync data

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#271]
### 💡 Description

- [x] update terraform scripts
- [x] deploy to production
- [x] setup roles
- [x] setup logstash to sync the data

**Comment by jordanpadams** [comment]
Status: Working with SAs for syncing the data to prod

**Comment by tloubrieu-jpl** [comment]
Some issues with bigger index.

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl keeps working on the ECS components. I will create a new ticket for @alexdunnjpl to work on the missing documents.

**Comment by tloubrieu-jpl** [comment]
@alexdunnjpl has made the migration of the remaining documents to the production Opensearch serverless.

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl works on the infrastructure for authentication. After meeting the lambda authorizers are going to be simplified.

**Comment by nutjob4life** [comment]
Merging the lambda; next is IAM roles and Cognito

**Comment by jordanpadams** [comment]
Status: Working on getting identity pools/user pools deployed to production

**Comment by jordanpadams** [comment]
This is done. In production.

**Comment by nutjob4life** [comment]
Thanks @tloubrieu-jpl @sjoshi-jpl @jordanpadams! 🎉 

(And yes, the SAs too 😁)
