### ISSUE TITLE
As a data manager, I want to query OpenSearch Serverless from the command-line

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#273]
### Checked for duplicates

No - I haven't checked

### 🧑‍🔬 User Persona(s)

Node operator

### 💪 Motivation

...so that I can do operations which are not supported by harvest, registry-mgr or registry-api.

### 📖 Additional Details

Engineering Node need to provide a python script which will authenticate with Cognito and sign the URL request to OpenSearch.

Arguments will be:
- discipline node
- curl arguments (URL, header, query params)
- cognito login/password

### Acceptance Criteria
See https://github.com/NASA-PDS/registry/discussions/274
**Given** 
**When I perform** 
**Then I expect**

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl can provide to Alex:

- the dev opensearch host on MCP
- the cognito endpoint
- the cognito client id
- create one cognito user with access to opensearch dev, as for one node
- one index to query is `atm-delta-registry`. So a test request could be `/atm-delta-registry/_search`

**Comment by al-niessner** [comment]
@alexdunnjpl @jordanpadams @tloubrieu-jpl 

Probably means you want to move `<node>` from harvest and put it in the registry connection XML. Doing that allows registry-mgr to do `<node>-<index>-<suffix>` where needed and `<index>-<suffix>` where needed.

May need to expand the concept of the registry connection XML to have more than one node and index too.

**Comment by jordanpadams** [comment]
Status: Taking longer than expected, but in work. No blockers.

**Comment by alexdunnjpl** [comment]
Note to self - this is plan B for working while MT is blocked

**Comment by tloubrieu-jpl** [comment]
The prototype works, will be wrapped in a proper tool later.

**Comment by alexdunnjpl** [comment]
Blocked pending resolution of API Gateway interface discussion

**Comment by alexdunnjpl** [comment]
Per breakout discussion

- gateway will be left untouched, as it is currently required to fill missing features in the Java SDK (negotiating access token for credentials from an identity service)
- anon use is out of scope for this ticket
- gateway is not related to or required by the intended auth flow for the request client.  Client should get cognito token with user/pass, negotiate for creds, and then hit OpenSearch directly

Follow-up with @sjoshi-jpl will be necessary to iron out any outstanding IAM grants/issues.

**Comment by tloubrieu-jpl** [comment]
This still needs to be packaged.

**Comment by alexdunnjpl** [comment]
Implemented as https://github.com/NASA-PDS/serverless-opensearch-request-signer

**Comment by tloubrieu-jpl** [comment]
@tloubrieu-jpl will test it.

**Comment by nutjob4life** [comment]
@tloubrieu-jpl reminder to test it

**Comment by tloubrieu-jpl** [comment]
The tool is developed in a new repository: https://github.com/NASA-PDS/registry-client
