### ISSUE TITLE
harvest created archive_status as an array and registry-mgr updates it as a string

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#276]
### Checked for duplicates

No - I haven't checked

### 🐛 Describe the bug

When I looked at the test opensearch loaded by the docker compose script, I've noticed this discrepency.

### 🕵️ Expected behavior

I expected the field to alway have the same type.

Maybe list ? To be confirmed.

### 📜 To Reproduce

Use the docker compose deployment.

In opensearch, with query `https://elasticsearch:9200/registry/_search?size=100` can see:

    ...archive_status="archived"

and 

    ...archive_status=["staged"]

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

Did you ever confirm which is correct?

**Comment by al-niessner** [comment]
@tloubrieu-jpl 

Set back to array because that is what the original code did.
