### ISSUE TITLE
Copy data necessary for web mod efforts to search-en registry prior to shutdown

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#277]
### 💡 Description

We need to make sure all the data needed by @anilnatha for the web mod demo has been copied over to the search-en registry prior to shutting down the opensearch clusters.

### ⚔️ Parent Epic / Related Tickets

Parent: #185

### Sub-tasks
- [ ] Identify the data sets and the node cluster they are located in
- [ ] Copy that data (collections and bundles only right now) over to search-en cluster (or just download all the labels and harvest the data)

**Comment by tloubrieu-jpl** [comment]
first step: identify the bundles/collections needed for web mod: 
- voyager (SBN, GEO, ATM, RMS, PPI), the list of bundle needed are [6:58 PM] Padams, Jordan H (US 398A)
https://pds.nasa.gov/api/search/1/products?q=((ref_lid_investigation%20eq%20%22urn:nasa:pds:context:investigation:mission.voyager%22)%20and%20(product_class%20eq%20%22Product_Bundle%22))&fields=ops:Harvest_Info.ops:node_name

- msl (), 
- context products (EN and PSA ?)

options1 : download from node and re-harvest
option 2: migrate from opensearch to opensearch (logstash)

**Comment by tloubrieu-jpl** [comment]
For each managed opensearch
registry --> index node-registry in serverless
registryRef --> index node-registryRef in serverless
registryDD  --> index node-registryDD in serverless

**Comment by jordanpadams** [comment]
This was done. migration completed.
