### ISSUE TITLE
Create GIS collection PDS4 label

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#284]
### 💡 Description

Create PDS4 for GIS service for https://trek.nasa.gov/tiles/apidoc/ for Titan Treks using Oxygen, see PDS4 label example for Mars Treks https://pds.nasa.gov/data/pds4/context-pds3/service/Product/mars_trek_1.0.xml

**Comment by nutjob4life** [comment]
Basically done! Looking for feedback
