### ISSUE TITLE
Create the PDS4 service labels for the dataset served by GIS services

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#285]
### 💡 Description

Write a script which created PDS4 labels for the data published in Treks WMTS, input is likely to be something like, specifically for Titan, https://trek.nasa.gov/tiles/Titan/EQ/TitanISS2018June.proj.scale/1.0.0/WMTSCapabilities.xml

**Comment by nutjob4life** [comment]
Will meet with @tloubrieu-jpl after the breakout to go over a few things

**Comment by tloubrieu-jpl** [comment]
We switched to using Product_Service instead.
We will discuss at the breakout how to add that as an interim solution before the PDS4 IM is updated.
