### ISSUE TITLE
As an administrator of the registry, I don't want ENG operator loading data to have administration authorizations

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#309]
### 💡 Description

We need to have 2 distinct groups for ENG node:
- admin: authorized to create indexes...
- operator: only read/write in the en-* indexes

**Comment by sjoshi-jpl** [comment]
We can have a PDS_ADMIN_USERS and PDS_ENG_USERS, both tied to different IAM roles. The ENG IAM role will only have read/write access to en-* indexes.

**Comment by tloubrieu-jpl** [comment]
@sjoshi-jpl I will close this ticket since the roles are created in production.
However, we should eventually have a terraform script and a commit or PR to attach to the closed ticket or a link to a documentation. As a dev team this is inconfortable to close tickets without a produced artifact.
