### ISSUE TITLE
Upgrade the initialization of the ES/OS database following latest upgrade of components

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#31]
## 💪 Motivation
Since Eugene updated harvest and registry manager and registry-api we will need to update the initialization of the database:
-	Registry-manager load-data is moved to harvest (https://github.com/NASA-PDS/registry-harvest-cli/pull/11)
-	Harvest load data with archive status = staged and registry-api shows only archived and registered status. We need to apply registry-manager set status on the loaded bundle. (https://github.com/NASA-PDS/registry-api/pull/99)

Some of the integration test do not work because of that.

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by ramesh-maddegoda** [comment]
Created and merged 3 pull requests for set-archive-status in ES/OS database related work.
1)  https://github.com/NASA-PDS/registry-loader/pull/10
2) https://github.com/NASA-PDS/registry-harvest-cli/pull/12
3) https://github.com/NASA-PDS/registry/pull/33
