### ISSUE TITLE
SBN user no longer able to access test registry

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#336]
### Checked for duplicates

Yes - I've already checked

### 🐛 Describe the bug

Queries that were working are returning response like:

```
Making request to url: [https://p5qmxrldysl1gy759hqf.us-west-2.aoss.amazonaws.com/sbnumd-registry/_search](https://urldefense.us/v3/__https://p5qmxrldysl1gy759hqf.us-west-2.aoss.amazonaws.com/sbnumd-registry/_search__;!!PvBDto6Hs4WbVuu7!L5sNOYHXgxBxsHrabcgou5a4Dz4Ti3Ud1v53B70lTTSc4PcraLB_wT8XqsCJ9N6d8GNle4lU-TqT_O-W78PFdhO-hGI$)
Including POST body: {"query": {"simple_query_string": {"query": "urn:nasa:pds:dart*"}}}
Including headers: {"Content-Type": "application/json"}
{
  "error": {
    "root_cause": [
      {
        "type": "security_exception",
        "reason": "Bad Authorization"
      }
    ],
    "type": "search_phase_execution_exception",
    "reason": "all shards failed",
    "phase": "query",
    "grouped": true,
    "failed_shards": []
  },
  "status": 403
}
```

### 🕵️ Expected behavior

Tests were working before

### 📜 To Reproduce

Query using registry client

### 🖥 Environment Info

- Version of this software [e.g. vX.Y.Z]
- Operating System: [e.g. MacOSX with Docker Desktop vX.Y]
...

### 🦄 Related requirements

🦄 #xyz

**Comment by tloubrieu-jpl** [comment]
@plawton-umd says it works again today.

Before it failed, last it worked was Spet 27th 2024.

I will close the ticket since it works now.
