### ISSUE TITLE
Propose a solution for set-archive-status on a docker compose deployment

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#34]
## 💪 Motivation
...so that I can manually set the archive status of a product stored in a registry deployed through docker compose.

## 📖 Additional Details

The current issue is that it requires some workaround to enable registry-manager deployed natively to interact with docker compose deployed opensearch because of SSL certificate validation.

The solution is:
- either to detail a working workaround to make docker hosted SSL certificate work for native host request (e.g. hostname == elasticsearch).
- or to enable set-archive-status operation through a docker compose enabled command. 

## ⚖️ Acceptance Criteria
**Given** 
**When I perform** 
**Then I expect**

**Comment by tloubrieu-jpl** [comment]
Before we work on that, we need to make plans on how to deploy these container in a production environment since docker compose is only on the single node.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl is this still something we need to look into?

**Comment by tloubrieu-jpl** [comment]
The multiple set-archive-status operations are applied to the integration dataset as coded here https://github.com/NASA-PDS/registry-loader/blob/main/docker/entrypoint.sh#L59-L60

This ticket will be closed with that.

**Comment by tloubrieu-jpl** [comment]
We are able set status archive status within the docker loader image, no need to implement that call from outside the docker image (e.g. in docker compose)
