### ISSUE TITLE
Develop script to update existing registry metadata per B12.1 metadata modifications

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#43]
## 💡 Description
- [x] Review [B12.1 RDD](https://nasa-pds.github.io/releases/12.1/rdd.html) 
- [x] Identify issues / updates that impacted product metadata
- [x] Write script to update those metadata fields to match the upgrades from B12.1

## Changes
- [x] Added `upgrade-dd` command to Registry manager to upgrade data dictionary (https://github.com/NASA-PDS/registry-mgr/pull/47)
- [x] Created a Unix shell script to add `ops:Tracking_Meta/ops:archive_status` field (https://github.com/NASA-PDS/registry-loader/pull/13)

**Comment by jordanpadams** [comment]
@jimmie to verify, you ran both the command from https://github.com/NASA-PDS/registry-mgr/pull/47 and the script at https://github.com/NASA-PDS/registry-loader/pull/13 to both update the schemas and update the metadata?

**Comment by jimmie** [comment]
All data dictionaries have been upgraded (w/ -r). Version history of registry deployments is captured here: https://wiki.jpl.nasa.gov/display/PDSEN/AWS+Node+Registries.

It looks like this PR is safe to merge.

**Comment by jordanpadams** [comment]
all PRs merged, sub-tasks completed
