### ISSUE TITLE
Support LBLX extension in Registry Loader tools

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#47]
## 💡 Description

Per CCB-260: https://pds-jira.jpl.nasa.gov/browse/CCB-260

See validate requirement for more details: https://github.com/nasa-pds/validate/issues/482

**Comment by jordanpadams** [comment]
📆 May status: Not started

**Comment by tloubrieu-jpl** [comment]
@jordanpadams what is that extension, do we have a link to the CCB-260, it is on JIRA I think but I am not finding a link

**Comment by jordanpadams** [comment]
@tloubrieu-jpl see attached. that extension is new PDS4 extension specific to PDS. so if you have never seen it before, its because it has never been used. all of our tools need to support it by end of this build. add link to validate for more details on what is expected.

**Comment by tloubrieu-jpl** [comment]
Yes, thanks @jordanpadams I think I understand, everything work the same exect that xml pds4 label extension is .lblx instead of .xml.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl slight catch is it can differ by collection within a bundle 😄 . so we will need to allow for it to be configurable in kind of a funky way. similar to validate I am thinking:

- new file extension flag for `xml` and `lblx` (default `xml`)
- if a collection differs, new flag to specify path to data where the extensions will be different (or introduce `--exclude` flag to exclude the path where the extension differs, and have them run harvest again on the separate path?

**Comment by jordanpadams** [comment]
📆 June status: Delayed 1-2 sprints due to loss of staff.

**Comment by jordanpadams** [comment]
📆 July status: Deferred due to loss of personnel

**Comment by jordanpadams** [comment]
Done per https://github.com/NASA-PDS/harvest/issues/130

**Comment by jordanpadams** [comment]
@msbentley sorry! this was as duplicate of https://github.com/NASA-PDS/harvest/issues/129
