### ISSUE TITLE
Re-imagine Registry Handling of Product Versioning

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#55]
## 💡 Description

How do can we track in the registry product identifiers and versions when the actual product identifiers/versions according to their metadata do not match up?

Context products are a prime example of this, but also starting to occur for actual products.

Initial proposed solution:
* design a method for users to specify `supersedes` in the product metadata OR via a product_metadata_supplemental specific to superseding of data sets
   * should this be an LDD?
* create new index to track deprecated LIDs
* create new internal/ops unique identifier (UID) for each product in the registry that is auto-generated at the time of ingestion
* version tracking of the products is either determined upon ingestion or a new index (or graphDB?) is created to manage product versions
* Automate setting and management of of archive status across the archive

### General Example
`Product A` changes its logical identifier from version "1" of the product (`lid_x`) to version "2" (`lid_y`), we want to know that these are actually revisions of the same product.

NOTE: The versions may not be in appropriate ascending order, e.g. you could have `lid_x::1.0` and `lid_y::1.0`, but really `lid_x::1` == `Product A v1` and `lid_y::1.0` == `Product A v2`

## Real Example
The logical identifier for the Cosmic Ray Subsystem Instrument context product was changed at some point to meet the new context product LID guidelines.

So the context product with LIDVID [urn:nasa:pds:context:instrument:crs.vg1::1.0](https://pds.nasa.gov/data/pds4/context-pds4/instrument/vg1.crs_1.0_deprecated.xml) was superseded by LIDVID [urn:nasa:pds:context:instrument:vg1.crs::1.0](https://pds.nasa.gov/data/pds4/context-pds4/instrument/vg1.crs_1.0.xml)

**Comment by tloubrieu-jpl** [comment]
@jordanpadams can we table that for this sprint ? I don't feel like we will be able to finalize what Eugene started that soon.

**Comment by jordanpadams** [comment]
:calendar: June status: 75% complete. Awaiting pull request review and merge.

**Comment by jordanpadams** [comment]
📆 July status: Still 75% complete. Awaiting pull request review and merge. Implementation in API has been tabled until after https://github.com/nasa-pds/pds-api/issues/180

**Comment by jordanpadams** [comment]
https://github.com/NASA-PDS/registry-mgr/pull/46 was merged
