### ISSUE TITLE
Populate EN Registry

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#61]

**Comment by jordanpadams** [comment]
📆 May status: Not started

**Comment by jordanpadams** [comment]
:calendar: June status: In progress

**Comment by jordanpadams** [comment]
📆 July status: In progress. On schedule

**Comment by jordanpadams** [comment]
📆 August status: Still in work. Awaiting update to EN processes to ingest all data products.

**Comment by jordanpadams** [comment]
📆 September status: Still in work. Will not delay build. Operations task.

**Comment by jordanpadams** [comment]
@viviant100 can we check where we are at with this?

**Comment by viviant100** [comment]
@rchenatjpl to do it first and we can update the process later.  This week will be great. Let us know if you run into any issues.  Thanks.

**Comment by rchenatjpl** [comment]
I'd say I'm done with this.
