### ISSUE TITLE
Use AWS Cognito for authentication of users who connect to the Registry's OpenSearch

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#65]
We want to use cognito for the uathentication of users who access the OpenSearch components of the registry,

**Comment by tloubrieu-jpl** [comment]
We discussed that during the SA meeting.

Cognito can be used to authenthicate kibana but not the direct access to the OpenSearch API.

**Comment by jordanpadams** [comment]
@tloubrieu-jpl @viviant100 this has been completed, correct? Or is this some future task?

**Comment by tloubrieu-jpl** [comment]
Right @jordanpadams , this is completed since the tickets within the EPICs are closed. Note that we were not able to do that, until AWS supported Cognito as authentication or its opensearch managed service.
