### ISSUE TITLE
when docker compose starts, registry-api docker is missing curl

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/registry#69]
## 🐛 Describe the bug

Curl is used for the registry-api to wait for opensearch to be up. Curl is missing in the docker image used by the registry api.

## 📜 To Reproduce
1. `cd docker`
2. `docker compose --profile=int-registry-service-loader up`
3. See error in console:

```
docker-registry-api-1                        | /usr/local/registry-api-service/registry-api-waits-for-elasticsearch.sh: 45: curl: not found
docker-registry-api-1                        | waiting for elasticsearch

```

## 🕵️ Expected behavior

The full registry should start, including the registry-api

## 📚 Version of Software Used

1.1.0-SNAPSHOT

## 🖥 System Info

---

**Comment by gxtchen** [comment]
@tloubrieu-jpl @viviant100 I tried with registry-1.1.0.deve0-dev as well as git clone from the main branch, both versions still giving the waiting fore elasticsearch messages.

**Comment by tloubrieu-jpl** [comment]
Hi @gxtchen , actually waiting is  not the issue, it is the nromal process that this components wait for elasticsearch until it is ready. The error was that `curl` which is used to test the availability of elaticsearch was not available in the docker image, the message was:

     /usr/local/registry-api-service/registry-api-waits-for-elasticsearch.sh: 45: curl: not found

do you still have that ?

Thanks,

Thomas

**Comment by gxtchen** [comment]
@tloubrieu-jpl no, I don't see that any more. But docker is waiting for elasticsearch for ever, is this normal?

**Comment by tloubrieu-jpl** [comment]
Thanks @gxtchen , no that is not normal. I believe we can close this ticket though. Can you open a different ticket in the registry repository with the full logs of the docker compose stdout ? Thanks
