### ISSUE TITLE
Missing INSIGHT LDD v1600

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/registry#84]
## 🐛 Describe the bug

From user:

> I ran the harvest on the Insight twins_bundle and ps_bundle and here's the error message:

> [INFO] Downloading https://pds.nasa.gov/pds4/mission/insight/v1/PDS4_INSIGHT_1600.JSON to /tmp/LDD-10130100108337750353.JSON 404 - Not Found

---

## ⚙️ Engineering Details
- [x] generate LDD
- [x] post on website - https://github.com/NASA-PDS/portal-tasks/issues/40

**Comment by jordanpadams** [comment]
JSON is contained in this ZIP [PDS4_INSIGHT_1600.zip](https://github.com/NASA-PDS/registry/files/9300948/PDS4_INSIGHT_1600.zip)

**Comment by jordanpadams** [comment]
FYI, generated by:
1. cloned ldd-insight repo: https://github.com/pds-data-dictionaries/ldd-insight 
2. found old IngestLDD file archived here: https://github.com/pds-data-dictionaries/ldd-insight/tree/main/archive/src/1.6.0.0
3. ran LDDTool on the IngestLDD:
```
lddtool -V 1B00 -lpJ INSIGHT_lddtool.xml
```
4. renamed the file to match the old file naming scheme.
5. created ZIP with JSON and other necessary files

**Comment by c-suh** [comment]
Resolved with https://github.com/NASA-PDS/portal-tasks/issues/40.
