### ISSUE TITLE
https://.../api/search/1.0/products still sees data deleted by registry-manager

### ISSUE THREAD

**Issue by rchenatjpl** [NASA-PDS/registry#98]
## 🐛 Describe the bug
After
% harvest
% registry-manager set-archive-status -status archived -lidvid thebundle'sLIDVID
% registry-manager delete-data -all
The bundle's LID is no longer searchable
  https://pds.nasa.gov/api/search/1.0/products/urn:nasa:pds:context::1.3
but the products below it linger:
  https://pds.nasa.gov/api/search/1.0/products/urn:nasa:pds:context:investigation:field_campaign.dd_eldorado_nv_2015::1.0

## 📜 To Reproduce
I can't reproduce this without manually editing files since I can't clear whatever database

## 🕵️ Expected behavior
This behavior might be intentional. For my testing, it would be very helpful to be able to delete everything, but there may be other considerations

## 📚 Version of Software Used
Harvest version: 3.6.0
Build time: 2022-04-13T17:42:54Z
Registry Manager version: 4.4.0
Build time: 2022-04-13T18:24:45Z

## 🖥 System Info

---

**Comment by jordanpadams** [comment]
@rchenatjpl the registry manager unfortunately does not yet support the ability to delete an entire bundle by bundle's lidvid. Mike Drum submitted a requirement for this here: https://github.com/NASA-PDS/registry-mgr/issues/52

**Comment by rchenatjpl** [comment]
Oh, yes, deleting an entire bundle by the bundle's lidvid would be very helpful.

But is this issue separate? I want to delete all data from my registry, regardless of bundle.

**Comment by jordanpadams** [comment]
@rchenatjpl I don't think we have a function right now to do this. You need to delete all the packages individually by package_id, or you can interact with OpenSearch directly using the [Delete by query API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html)
